server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amigaura/DataflowExtConfigRepos
          username: amigaura

          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"